import Nav from "@/components/Nav";
import "@/styles/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "FakeReddit",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="h-full w-full bg-neutral-800 text-white">
          <img
            src="https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?q=80&w=1493&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
            alt=""
            className="absolute -z-10 w-screen h-screen object-cover brightness-75"
          />
          <Nav />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
