import Nav from "@/components/Nav";
import "@/styles/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "FakeReddit",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="h-full w-full bg-neutral-800 text-white scrollbar-hide">
          <img
            src="/images/blkgld.jpg"
            alt=""
            className="fixed -z-10 w-screen h-screen object-cover brightness-75 blur-[6px]"
          />
          <Nav />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
